
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { ThemeProvider } from 'next-themes';
import Head from "next/head";


export const metadata = {
  title: "AI Chatbot",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", 
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={` antialiased `}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {children}
          <ToastContainer />
        </ThemeProvider>
        
      </body>
    </html>
  );
}
