
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { ThemeProvider } from 'next-themes';


export const metadata = {
  title: "AI Chatbot",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <ToastContainer />
        </ThemeProvider>
        
      </body>
    </html>
  );
}
